source('ee_sim.R')
source('print_state.R')

state <- Initialize.State(61)
printState(state)

state <- Build(state, farms = state$buildings.per.turn)
printState(state)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, construction = 1)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
state <- Build(state, farms = state$buildings.per.turn)
printState(state)

printState(state)
state <- Build(state, enterprize = state$buildings.per.turn)
printState(state)

state <- Explore(state, turns=50)
printState(state)
